--------------------------------------------------------
--  文件已创建 - 星期二-十月-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SYS_DICT
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_DICT" 
   (	"ID" VARCHAR2(32 BYTE), 
	"PARENT_ID" VARCHAR2(32 BYTE) DEFAULT 0, 
	"VALUE" VARCHAR2(100 BYTE), 
	"LABEL" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"SORT" NUMBER(10,0) DEFAULT 0, 
	"DEL_FLAG" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."ID" IS '主键ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."PARENT_ID" IS '父ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."VALUE" IS '字典编码';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."LABEL" IS '编码名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."TYPE" IS '字典类别';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."DESCRIPTION" IS '描述';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."SORT" IS '排序';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_DICT"."DEL_FLAG" IS '是否删除 0否 1是';
--------------------------------------------------------
--  DDL for Table SYS_FILE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_FILE" 
   (	"FILE_ID" VARCHAR2(32 BYTE), 
	"FILE_NAME" VARCHAR2(1000 BYTE), 
	"FILE_TYPE" VARCHAR2(50 BYTE), 
	"FILE_FORMAT" VARCHAR2(50 BYTE), 
	"URL" VARCHAR2(200 BYTE), 
	"INS_TIME" DATE DEFAULT SYSDATE, 
	"CREATE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE"."FILE_ID" IS '主键ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE"."FILE_NAME" IS '文件名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE"."FILE_TYPE" IS '文件类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE"."FILE_FORMAT" IS '文件格式';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE"."URL" IS '保存路径';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE"."INS_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE"."CREATE_ID" IS '创建者';
--------------------------------------------------------
--  DDL for Table SYS_FILE_RELATION
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_FILE_RELATION" 
   (	"RELATION_ID" VARCHAR2(32 BYTE), 
	"FILE_ID" VARCHAR2(32 BYTE), 
	"FILE_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE_RELATION"."RELATION_ID" IS '材料关联ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE_RELATION"."FILE_ID" IS '文件ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_FILE_RELATION"."FILE_TYPE" IS '文件类型';
--------------------------------------------------------
--  DDL for Table SYS_MENU
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_MENU" 
   (	"MENU_ID" VARCHAR2(32 BYTE), 
	"PARENT_ID" VARCHAR2(32 BYTE), 
	"MENU_NAME" VARCHAR2(100 BYTE), 
	"SORT" NUMBER(10,0), 
	"URL" VARCHAR2(1000 BYTE), 
	"ICON" VARCHAR2(100 BYTE), 
	"IS_SHOW" CHAR(1 BYTE), 
	"REMARK" VARCHAR2(100 BYTE), 
	"PERMISSION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."MENU_ID" IS '菜单ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."PARENT_ID" IS '父ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."MENU_NAME" IS '菜单名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."SORT" IS '顺序';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."URL" IS '路径';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."ICON" IS '图标';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."IS_SHOW" IS '是否在菜单中显示';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_MENU"."PERMISSION" IS '权限标识';
--------------------------------------------------------
--  DDL for Table SYS_NEWS
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_NEWS" 
   (	"NEWS_ID" VARCHAR2(32 BYTE), 
	"NEWS_CATEGORY" VARCHAR2(50 BYTE), 
	"NEWS_TYPE" VARCHAR2(50 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"NEWS_CONTENT" CLOB, 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" 
 LOB ("NEWS_CONTENT") STORE AS BASICFILE (
  TABLESPACE "AKS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_NEWS"."NEWS_ID" IS '新闻ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NEWS"."NEWS_CATEGORY" IS '新闻类别';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NEWS"."NEWS_TYPE" IS '新闻类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NEWS"."TITLE" IS '标题';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NEWS"."NEWS_CONTENT" IS '内容';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NEWS"."INS_TIME" IS '添加时间';
--------------------------------------------------------
--  DDL for Table SYS_NOTICE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_NOTICE" 
   (	"NOTICE_ID" VARCHAR2(32 BYTE), 
	"NOTICE_TITLE" VARCHAR2(100 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(2000 BYTE), 
	"NOTICE_SOURCE" VARCHAR2(100 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_NOTICE"."NOTICE_ID" IS '主键ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NOTICE"."NOTICE_TITLE" IS '通知标题';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NOTICE"."NOTICE_CONTENT" IS '通知内容';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NOTICE"."NOTICE_SOURCE" IS '通知来源';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_NOTICE"."INS_TIME" IS '通知时间';
--------------------------------------------------------
--  DDL for Table SYS_REGION
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_REGION" 
   (	"REGION_ID" VARCHAR2(5 BYTE), 
	"REGION_CODE" VARCHAR2(20 BYTE), 
	"REGION_NAME" VARCHAR2(100 BYTE), 
	"PARENT_ID" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_REGION"."REGION_ID" IS '主键ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_REGION"."REGION_CODE" IS '行政区划代码';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_REGION"."REGION_NAME" IS '行政区划名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_REGION"."PARENT_ID" IS '父行政区划';
--------------------------------------------------------
--  DDL for Table SYS_ROLE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_ROLE" 
   (	"ROLE_ID" VARCHAR2(32 BYTE), 
	"PARENT_ID" VARCHAR2(32 BYTE), 
	"ROLE_NO" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"DATA_SCOPE" VARCHAR2(50 BYTE), 
	"SORT" NUMBER(10,0), 
	"REMARK" VARCHAR2(100 BYTE), 
	"NODE_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."ROLE_ID" IS '角色ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."PARENT_ID" IS '父ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."ROLE_NO" IS '角色编号';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."NAME" IS '角色名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."DATA_SCOPE" IS '数据范围';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."SORT" IS '顺序';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE"."NODE_TYPE" IS '节点角色';
--------------------------------------------------------
--  DDL for Table SYS_ROLE_MENU
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_ROLE_MENU" 
   (	"ROLE_ID" VARCHAR2(32 BYTE), 
	"MENU_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';
--------------------------------------------------------
--  DDL for Table SYS_SMS_CODE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_SMS_CODE" 
   (	"SMS_CODE_ID" VARCHAR2(32 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"SMS_CODE" VARCHAR2(6 BYTE), 
	"SEND_TIME" DATE, 
	"SEND_TYPE" VARCHAR2(50 BYTE), 
	"VALID_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_CODE"."SMS_CODE_ID" IS '短信验证码ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_CODE"."PHONE" IS '手机号';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_CODE"."SMS_CODE" IS '验证码';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_CODE"."SEND_TIME" IS '发送时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_CODE"."SEND_TYPE" IS '验证码发送类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_CODE"."VALID_TIME" IS '有效期';
--------------------------------------------------------
--  DDL for Table SYS_SMS_HIS
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_SMS_HIS" 
   (	"SMS_HIS_ID" VARCHAR2(32 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"SEND_TYPE" VARCHAR2(50 BYTE), 
	"SMS_CONTENT" VARCHAR2(1000 BYTE), 
	"THIRD_RESPONSE" VARCHAR2(500 BYTE), 
	"SEND_RESULT" VARCHAR2(1 BYTE), 
	"SEND_TIME" DATE, 
	"RESULT_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."SMS_HIS_ID" IS '主键ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."PHONE" IS '手机号';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."SEND_TYPE" IS '发送类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."SMS_CONTENT" IS '短信内容';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."THIRD_RESPONSE" IS '第三方返回内容';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."SEND_RESULT" IS '发送结果（1成功/0失败）';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."SEND_TIME" IS '发送时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_SMS_HIS"."RESULT_TIME" IS '发送返回结果时间';
--------------------------------------------------------
--  DDL for Table SYS_USER
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_USER" 
   (	"USER_ID" VARCHAR2(32 BYTE), 
	"USER_TYPE" VARCHAR2(50 BYTE), 
	"USER_STATUS" VARCHAR2(50 BYTE), 
	"LOGIN_NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"HEAD_PORTRAIT" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"UPDATE_TIME" DATE, 
	"INS_TIME" DATE, 
	"CREATE_ID" VARCHAR2(32 BYTE), 
	"DEL_FLAG" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."USER_ID" IS '用户ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."USER_TYPE" IS '用户类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."USER_STATUS" IS '用户状态';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."LOGIN_NAME" IS '账号';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."PASSWORD" IS '密码';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."NAME" IS '用户名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."HEAD_PORTRAIT" IS '头像';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."PHONE" IS '联系电话';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."DESCRIPTION" IS '备注';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."UPDATE_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."INS_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."CREATE_ID" IS '创建人';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER"."DEL_FLAG" IS '删除标志，默认是0，删除为1';
--------------------------------------------------------
--  DDL for Table SYS_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_USER_ROLE" 
   (	"USER_ID" VARCHAR2(32 BYTE), 
	"ROLE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER_ROLE"."USER_ID" IS '用户ID（单位用户/监管单位用户）';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_USER_ROLE"."ROLE_ID" IS '角色ID';
--------------------------------------------------------
--  DDL for Table SYS_VIEW_NOTICE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_VIEW_NOTICE" 
   (	"USER_ID" VARCHAR2(32 BYTE), 
	"NOTICE_ID" VARCHAR2(32 BYTE), 
	"NOTICE_STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_VIEW_NOTICE"."USER_ID" IS '用户ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_VIEW_NOTICE"."NOTICE_ID" IS '消息通知ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_VIEW_NOTICE"."NOTICE_STATUS" IS '消息通知状态';
--------------------------------------------------------
--  DDL for Table SYS_WAIT_HANDLE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" 
   (	"WAIT_HANDLE_ID" VARCHAR2(32 BYTE), 
	"WAIT_HANDLE_TYPE" VARCHAR2(50 BYTE), 
	"PARAM" VARCHAR2(1000 BYTE), 
	"SOURCE" VARCHAR2(200 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"WAIT_HANDLE_STATUS" VARCHAR2(50 BYTE), 
	"INS_TIME" DATE, 
	"RELATION_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."WAIT_HANDLE_ID" IS '主键ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."WAIT_HANDLE_TYPE" IS '待办事项类别';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."PARAM" IS '需要的参数';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."SOURCE" IS '来源';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."USER_ID" IS '处理人';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."WAIT_HANDLE_STATUS" IS '处理状态';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."INS_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."SYS_WAIT_HANDLE"."RELATION_ID" IS '关联ID（整改通知ID、投诉Id）';
--------------------------------------------------------
--  DDL for Table TRIP_BIKE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_BIKE" 
   (	"BIKE_ID" VARCHAR2(32 BYTE), 
	"BIKE_NAME" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"LNG" NUMBER(10,6), 
	"LAT" NUMBER(10,6), 
	"TOTAL_NUM" NUMBER(*,0), 
	"PARK_NUM" NUMBER(*,0), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."BIKE_ID" IS '停车场ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."BIKE_NAME" IS '停车场名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."ADDRESS" IS '位置';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."LNG" IS '经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."LAT" IS '纬度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."TOTAL_NUM" IS '总数量';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."PARK_NUM" IS '停放数量';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BIKE"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_BUS_COLLECTION
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_BUS_COLLECTION" 
   (	"BUS_COLLECTION_ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"COLLECTION_TYPE" VARCHAR2(50 BYTE), 
	"LINE_ID" VARCHAR2(32 BYTE), 
	"LINE_NAME" VARCHAR2(200 BYTE), 
	"STATION_NAME" VARCHAR2(200 BYTE), 
	"BEGIN_STATION" VARCHAR2(200 BYTE), 
	"END_STATION" VARCHAR2(200 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."BUS_COLLECTION_ID" IS '收藏ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."USER_ID" IS '用户ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."COLLECTION_TYPE" IS '收藏类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."LINE_ID" IS '线路ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."LINE_NAME" IS '线路名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."STATION_NAME" IS '站点名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."BEGIN_STATION" IS '开始站点';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."END_STATION" IS '结束站点';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_BUS_COLLECTION"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_CARD
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_CARD" 
   (	"CARD_ID" VARCHAR2(32 BYTE), 
	"CARD_NAME" VARCHAR2(200 BYTE), 
	"SERVICE_PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"LNG" NUMBER(10,6), 
	"LAT" NUMBER(10,6), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CARD"."CARD_ID" IS '一卡通ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CARD"."CARD_NAME" IS '一卡通名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CARD"."SERVICE_PHONE" IS '服务电话';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CARD"."ADDRESS" IS '位置';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CARD"."LNG" IS '经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CARD"."LAT" IS '纬度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CARD"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_CHARGE_PILE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" 
   (	"CHARGE_PILE_ID" VARCHAR2(32 BYTE), 
	"CHANGE_PILE_NAME" VARCHAR2(200 BYTE), 
	"SINGLE_PRICE" NUMBER(11,2), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"LNG" NUMBER(10,6), 
	"LAT" NUMBER(10,6), 
	"CHANGE_PILE_STATUS" VARCHAR2(50 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."CHARGE_PILE_ID" IS '充电桩ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."CHANGE_PILE_NAME" IS '充电桩名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."SINGLE_PRICE" IS '单价';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."ADDRESS" IS '位置';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."LNG" IS '经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."LAT" IS '纬度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."CHANGE_PILE_STATUS" IS '充电桩状态';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CHARGE_PILE"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_CUSTOM_BUS
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" 
   (	"CUSTOM_BUS_ID" VARCHAR2(32 BYTE), 
	"LINE_NAME" VARCHAR2(200 BYTE), 
	"DEPART_TIME" DATE, 
	"BEGIN_STATION" VARCHAR2(200 BYTE), 
	"END_STATION" VARCHAR2(200 BYTE), 
	"LINE_STATUS" VARCHAR2(50 BYTE), 
	"VOTE_NUM" NUMBER(*,0), 
	"CREATE_ID" VARCHAR2(32 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."CUSTOM_BUS_ID" IS '定制公交ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."LINE_NAME" IS '线路名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."DEPART_TIME" IS '发车时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."BEGIN_STATION" IS '开始站点';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."END_STATION" IS '结束站点';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."LINE_STATUS" IS '线路状态';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."VOTE_NUM" IS '投票数量';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."CREATE_ID" IS '创建人';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_CUSTOM_BUS"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_ORDER
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_ORDER" 
   (	"ORDER_ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"ORDER_NO" VARCHAR2(50 BYTE), 
	"ORDER_TYPE" VARCHAR2(50 BYTE), 
	"ORDER_STATUS" VARCHAR2(50 BYTE), 
	"TOTAL_PRICE" NUMBER(11,2), 
	"PAY_TIME" DATE, 
	"INS_TIME" DATE, 
	"PAY_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."ORDER_ID" IS '订单ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."USER_ID" IS '用户ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."ORDER_NO" IS '订单编号';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."ORDER_TYPE" IS '订单类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."ORDER_STATUS" IS '订单状态';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."TOTAL_PRICE" IS '订单金额';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."PAY_TIME" IS '支付时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."INS_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER"."PAY_TYPE" IS '支付方式';
--------------------------------------------------------
--  DDL for Table TRIP_ORDER_STATUS
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_ORDER_STATUS" 
   (	"ORDER_ID" VARCHAR2(32 BYTE), 
	"ORDER_STATUS" VARCHAR2(50 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER_STATUS"."ORDER_ID" IS '订单ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER_STATUS"."ORDER_STATUS" IS '订单状态';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_ORDER_STATUS"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_PARKING
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_PARKING" 
   (	"PARKING_ID" VARCHAR2(32 BYTE), 
	"PARKING_NAME" VARCHAR2(200 BYTE), 
	"SINGLE_PRICE" NUMBER(11,2), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"LNG" NUMBER(10,6), 
	"LAT" NUMBER(10,6), 
	"PARING_STATUS" VARCHAR2(50 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."PARKING_ID" IS '停车场ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."PARKING_NAME" IS '停车场名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."SINGLE_PRICE" IS '单价';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."ADDRESS" IS '位置';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."LNG" IS '经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."LAT" IS '纬度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."PARING_STATUS" IS '停车场状态';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_PARKING"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_RENT_CAR_ORDER
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" 
   (	"RENT_CAR_ORDER_ID" VARCHAR2(32 BYTE), 
	"BEGIN_ADDRESS" VARCHAR2(500 BYTE), 
	"END_ADDRESS" VARCHAR2(500 BYTE), 
	"BEGIN_TIME" DATE, 
	"END_TIME" DATE, 
	"SEAT_NUM" NUMBER(*,0), 
	"CONTACTS_PHONE" VARCHAR2(20 BYTE), 
	"CONTACTS_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"DRIVER_NAME" VARCHAR2(50 BYTE), 
	"DRIVER_PHONE" VARCHAR2(20 BYTE), 
	"CAR_TYPE" VARCHAR2(100 BYTE), 
	"LICENSE_PLATE" VARCHAR2(20 BYTE), 
	"INVOICE_NAME" VARCHAR2(200 BYTE), 
	"INVOICE_NO" VARCHAR2(50 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."RENT_CAR_ORDER_ID" IS '包车订单ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."BEGIN_ADDRESS" IS '起点名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."END_ADDRESS" IS '终点名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."BEGIN_TIME" IS '用车开始时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."END_TIME" IS '用车结束时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."SEAT_NUM" IS '用车人数';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."CONTACTS_PHONE" IS '联系人电话';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."CONTACTS_NAME" IS '联系人';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."DESCRIPTION" IS '描述';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."DRIVER_NAME" IS '司机名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."DRIVER_PHONE" IS '司机联系电话';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."CAR_TYPE" IS '车辆类型';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."LICENSE_PLATE" IS '车牌号码';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."INVOICE_NAME" IS '发票名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."INVOICE_NO" IS '税号';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_RENT_CAR_ORDER"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_STATION
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_STATION" 
   (	"STATION_ID" VARCHAR2(32 BYTE), 
	"CUSTOM_BUS_ID" VARCHAR2(32 BYTE), 
	"DEPART_TIME" DATE, 
	"STATION_NAME" VARCHAR2(200 BYTE), 
	"ORDER_NUM" NUMBER(*,0), 
	"CREATE_ID" VARCHAR2(32 BYTE), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_STATION"."STATION_ID" IS '站点ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_STATION"."CUSTOM_BUS_ID" IS '定制公交ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_STATION"."DEPART_TIME" IS '发车时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_STATION"."STATION_NAME" IS '站点名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_STATION"."ORDER_NUM" IS '序号';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_STATION"."CREATE_ID" IS '创建人';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_STATION"."INS_TIME" IS '创建时间';
 
   COMMENT ON TABLE "IKEY_AKS"."TRIP_STATION"  IS '定制公交';
--------------------------------------------------------
--  DDL for Table TRIP_TAXI_DRIVER
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_TAXI_DRIVER" 
   (	"TAXI_DRIVER_ID" VARCHAR2(32 BYTE), 
	"LICENSE_PLATE" VARCHAR2(20 BYTE), 
	"STAR_NUM" NUMBER(2,1), 
	"ORDER_NUM" NUMBER(*,0), 
	"COMPANY_NAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_DRIVER"."TAXI_DRIVER_ID" IS '司机ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_DRIVER"."LICENSE_PLATE" IS '车牌号码';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_DRIVER"."STAR_NUM" IS '星级';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_DRIVER"."ORDER_NUM" IS '订单数';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_DRIVER"."COMPANY_NAME" IS '公司名称';
--------------------------------------------------------
--  DDL for Table TRIP_TAXI_EVALUATE
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" 
   (	"TAXI_EVALUATE_ID" VARCHAR2(32 BYTE), 
	"TAXI_ORDER_ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"EVALUATE_TYPE" VARCHAR2(200 BYTE), 
	"STAR_NUM" NUMBER(2,1), 
	"INS_TIME" DATE, 
	"CREATE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_EVALUATE"."TAXI_EVALUATE_ID" IS '服务评价ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_EVALUATE"."TAXI_ORDER_ID" IS '出租车订单ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_EVALUATE"."USER_ID" IS '用户ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_EVALUATE"."EVALUATE_TYPE" IS '评价类型【多选】';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_EVALUATE"."STAR_NUM" IS '星级';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_EVALUATE"."INS_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_EVALUATE"."CREATE_ID" IS '评价人';
--------------------------------------------------------
--  DDL for Table TRIP_TAXI_ORDER
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" 
   (	"TAXI_ORDER_ID" VARCHAR2(32 BYTE), 
	"TAXI_DRIVER_ID" VARCHAR2(32 BYTE), 
	"BEGIN_ADDRESS" VARCHAR2(200 BYTE), 
	"BEGIN_LNG" NUMBER(10,6), 
	"BEGIN_LAT" NUMBER(10,6), 
	"END_ADDRESS" VARCHAR2(200 BYTE), 
	"END_LNG" NUMBER(10,6), 
	"END_LAT" NUMBER(10,6), 
	"RECEIVE_ORDER_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."TAXI_ORDER_ID" IS '出租车订单ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."TAXI_DRIVER_ID" IS '司机ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."BEGIN_ADDRESS" IS '起点名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."BEGIN_LNG" IS '起点经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."BEGIN_LAT" IS '起点纬度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."END_ADDRESS" IS '终点名称';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."END_LNG" IS '终点经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."END_LAT" IS '终点纬度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_ORDER"."RECEIVE_ORDER_TIME" IS '接单时间';
--------------------------------------------------------
--  DDL for Table TRIP_TAXI_POSITION
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_TAXI_POSITION" 
   (	"TAXI_POSITION_ID" VARCHAR2(32 BYTE), 
	"TAXI_DRIVER_ID" VARCHAR2(32 BYTE), 
	"LNG" NUMBER(10,6), 
	"LAT" NUMBER(10,6), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_POSITION"."TAXI_POSITION_ID" IS '出租车位置ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_POSITION"."TAXI_DRIVER_ID" IS '司机ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_POSITION"."LNG" IS '经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_POSITION"."LAT" IS '维度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_POSITION"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Table TRIP_TAXI_TRAJECTORY
--------------------------------------------------------

  CREATE TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" 
   (	"TAXI_TRAJECTORY_ID" VARCHAR2(32 BYTE), 
	"TAXI_DRIVER_ID" VARCHAR2(32 BYTE), 
	"TAXI_ORDER_ID" VARCHAR2(32 BYTE), 
	"LNG" NUMBER(10,6), 
	"LAT" NUMBER(10,6), 
	"INS_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
 

   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_TRAJECTORY"."TAXI_TRAJECTORY_ID" IS '出租车订单轨迹ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_TRAJECTORY"."TAXI_DRIVER_ID" IS '出租车ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_TRAJECTORY"."TAXI_ORDER_ID" IS '出租车订单ID';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_TRAJECTORY"."LNG" IS '经度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_TRAJECTORY"."LAT" IS '纬度';
 
   COMMENT ON COLUMN "IKEY_AKS"."TRIP_TAXI_TRAJECTORY"."INS_TIME" IS '创建时间';
--------------------------------------------------------
--  DDL for Index PK_SYS_DICT
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_DICT" ON "IKEY_AKS"."SYS_DICT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_FILE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_FILE" ON "IKEY_AKS"."SYS_FILE" ("FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SUP_FILE_RELATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SUP_FILE_RELATION" ON "IKEY_AKS"."SYS_FILE_RELATION" ("RELATION_ID", "FILE_ID", "FILE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_MENU" ON "IKEY_AKS"."SYS_MENU" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_NEWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_NEWS" ON "IKEY_AKS"."SYS_NEWS" ("NEWS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_NOTICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_NOTICE" ON "IKEY_AKS"."SYS_NOTICE" ("NOTICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_REGION" ON "IKEY_AKS"."SYS_REGION" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_ROLE" ON "IKEY_AKS"."SYS_ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_ROLE_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_ROLE_MENU" ON "IKEY_AKS"."SYS_ROLE_MENU" ("ROLE_ID", "MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_SMS_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_SMS_CODE" ON "IKEY_AKS"."SYS_SMS_CODE" ("SMS_CODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_SMS_HIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_SMS_HIS" ON "IKEY_AKS"."SYS_SMS_HIS" ("SMS_HIS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_USER" ON "IKEY_AKS"."SYS_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_USER_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_USER_ROLE" ON "IKEY_AKS"."SYS_USER_ROLE" ("USER_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_VIEW_NOTICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_VIEW_NOTICE" ON "IKEY_AKS"."SYS_VIEW_NOTICE" ("USER_ID", "NOTICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_SYS_WAIT_HANDLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_SYS_WAIT_HANDLE" ON "IKEY_AKS"."SYS_WAIT_HANDLE" ("WAIT_HANDLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_BIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_BIKE" ON "IKEY_AKS"."TRIP_BIKE" ("BIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_BUS_COLLECTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_BUS_COLLECTION" ON "IKEY_AKS"."TRIP_BUS_COLLECTION" ("BUS_COLLECTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_CARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_CARD" ON "IKEY_AKS"."TRIP_CARD" ("CARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_CHARGE_PILE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_CHARGE_PILE" ON "IKEY_AKS"."TRIP_CHARGE_PILE" ("CHARGE_PILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_CUSTOM_BUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_CUSTOM_BUS" ON "IKEY_AKS"."TRIP_CUSTOM_BUS" ("CUSTOM_BUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_ORDER" ON "IKEY_AKS"."TRIP_ORDER" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_ORDER_STATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_ORDER_STATUS" ON "IKEY_AKS"."TRIP_ORDER_STATUS" ("ORDER_ID", "ORDER_STATUS", "INS_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_PARKING
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_PARKING" ON "IKEY_AKS"."TRIP_PARKING" ("PARKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_RENT_CAR_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_RENT_CAR_ORDER" ON "IKEY_AKS"."TRIP_RENT_CAR_ORDER" ("RENT_CAR_ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_STATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_STATION" ON "IKEY_AKS"."TRIP_STATION" ("STATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_TAXI_DRIVER
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_TAXI_DRIVER" ON "IKEY_AKS"."TRIP_TAXI_DRIVER" ("TAXI_DRIVER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_TAXI_EVALUATE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_TAXI_EVALUATE" ON "IKEY_AKS"."TRIP_TAXI_EVALUATE" ("TAXI_EVALUATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_TAXI_ORDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_TAXI_ORDER" ON "IKEY_AKS"."TRIP_TAXI_ORDER" ("TAXI_ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_TAXI_POSITION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_TAXI_POSITION" ON "IKEY_AKS"."TRIP_TAXI_POSITION" ("TAXI_POSITION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  DDL for Index PK_TRIP_TAXI_TRAJECTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "IKEY_AKS"."PK_TRIP_TAXI_TRAJECTORY" ON "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" ("TAXI_TRAJECTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS" ;
--------------------------------------------------------
--  Constraints for Table SYS_DICT
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_DICT" ADD CONSTRAINT "PK_SYS_DICT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("PARENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("VALUE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("LABEL" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("SORT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_DICT" MODIFY ("DEL_FLAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_FILE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_FILE" ADD CONSTRAINT "PK_SYS_FILE" PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE" MODIFY ("FILE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE" MODIFY ("FILE_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE" MODIFY ("FILE_FORMAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE" MODIFY ("URL" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE" MODIFY ("INS_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE" MODIFY ("CREATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_FILE_RELATION
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_FILE_RELATION" ADD CONSTRAINT "PK_SUP_FILE_RELATION" PRIMARY KEY ("RELATION_ID", "FILE_ID", "FILE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE_RELATION" MODIFY ("RELATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE_RELATION" MODIFY ("FILE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_FILE_RELATION" MODIFY ("FILE_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_MENU
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_MENU" ADD CONSTRAINT "PK_SYS_MENU" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_MENU" MODIFY ("PARENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_MENU" MODIFY ("MENU_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_MENU" MODIFY ("SORT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_MENU" MODIFY ("IS_SHOW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_NEWS
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_NEWS" ADD CONSTRAINT "PK_SYS_NEWS" PRIMARY KEY ("NEWS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_NEWS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NEWS" MODIFY ("NEWS_CATEGORY" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NEWS" MODIFY ("NEWS_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NEWS" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NEWS" MODIFY ("NEWS_CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NEWS" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_NOTICE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_NOTICE" ADD CONSTRAINT "PK_SYS_NOTICE" PRIMARY KEY ("NOTICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_NOTICE" MODIFY ("NOTICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NOTICE" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NOTICE" MODIFY ("NOTICE_SOURCE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_NOTICE" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_REGION
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_REGION" ADD CONSTRAINT "PK_SYS_REGION" PRIMARY KEY ("REGION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_REGION" MODIFY ("REGION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_REGION" MODIFY ("REGION_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_REGION" MODIFY ("REGION_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_REGION" MODIFY ("PARENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_ROLE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_ROLE" ADD CONSTRAINT "PK_SYS_ROLE" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE" MODIFY ("PARENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE" MODIFY ("ROLE_NO" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE" MODIFY ("SORT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE" MODIFY ("NODE_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_ROLE_MENU
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_ROLE_MENU" ADD CONSTRAINT "PK_SYS_ROLE_MENU" PRIMARY KEY ("ROLE_ID", "MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE_MENU" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_ROLE_MENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_SMS_CODE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_SMS_CODE" ADD CONSTRAINT "PK_SYS_SMS_CODE" PRIMARY KEY ("SMS_CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_CODE" MODIFY ("SMS_CODE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_CODE" MODIFY ("PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_CODE" MODIFY ("SMS_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_CODE" MODIFY ("SEND_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_CODE" MODIFY ("SEND_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_CODE" MODIFY ("VALID_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_SMS_HIS
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" ADD CONSTRAINT "PK_SYS_SMS_HIS" PRIMARY KEY ("SMS_HIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("SMS_HIS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("SEND_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("SMS_CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("THIRD_RESPONSE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("SEND_RESULT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("SEND_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_SMS_HIS" MODIFY ("RESULT_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USER
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_USER" ADD CONSTRAINT "PK_SYS_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("USER_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("USER_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("LOGIN_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("INS_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER" MODIFY ("CREATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_USER_ROLE" ADD CONSTRAINT "PK_SYS_USER_ROLE" PRIMARY KEY ("USER_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_VIEW_NOTICE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_VIEW_NOTICE" ADD CONSTRAINT "PK_SYS_VIEW_NOTICE" PRIMARY KEY ("USER_ID", "NOTICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_VIEW_NOTICE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_VIEW_NOTICE" MODIFY ("NOTICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_VIEW_NOTICE" MODIFY ("NOTICE_STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_WAIT_HANDLE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" ADD CONSTRAINT "PK_SYS_WAIT_HANDLE" PRIMARY KEY ("WAIT_HANDLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" MODIFY ("WAIT_HANDLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" MODIFY ("WAIT_HANDLE_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" MODIFY ("SOURCE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" MODIFY ("WAIT_HANDLE_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."SYS_WAIT_HANDLE" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_BIKE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" ADD CONSTRAINT "PK_TRIP_BIKE" PRIMARY KEY ("BIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("BIKE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("BIKE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("LAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("TOTAL_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("PARK_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BIKE" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_BUS_COLLECTION
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_BUS_COLLECTION" ADD CONSTRAINT "PK_TRIP_BUS_COLLECTION" PRIMARY KEY ("BUS_COLLECTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_BUS_COLLECTION" MODIFY ("BUS_COLLECTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BUS_COLLECTION" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_BUS_COLLECTION" MODIFY ("COLLECTION_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_CARD
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_CARD" ADD CONSTRAINT "PK_TRIP_CARD" PRIMARY KEY ("CARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_CARD" MODIFY ("CARD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CARD" MODIFY ("CARD_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CARD" MODIFY ("SERVICE_PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CARD" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CARD" MODIFY ("LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CARD" MODIFY ("LAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CARD" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_CHARGE_PILE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" ADD CONSTRAINT "PK_TRIP_CHARGE_PILE" PRIMARY KEY ("CHARGE_PILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("CHARGE_PILE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("CHANGE_PILE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("SINGLE_PRICE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("LAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("CHANGE_PILE_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CHARGE_PILE" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_CUSTOM_BUS
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" ADD CONSTRAINT "PK_TRIP_CUSTOM_BUS" PRIMARY KEY ("CUSTOM_BUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("CUSTOM_BUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("LINE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("DEPART_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("BEGIN_STATION" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("END_STATION" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("LINE_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("CREATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_CUSTOM_BUS" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_ORDER
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_ORDER" ADD CONSTRAINT "PK_TRIP_ORDER" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER" MODIFY ("ORDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER" MODIFY ("ORDER_NO" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER" MODIFY ("ORDER_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_ORDER_STATUS
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_ORDER_STATUS" ADD CONSTRAINT "PK_TRIP_ORDER_STATUS" PRIMARY KEY ("ORDER_ID", "ORDER_STATUS", "INS_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER_STATUS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER_STATUS" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_ORDER_STATUS" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_PARKING
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" ADD CONSTRAINT "PK_TRIP_PARKING" PRIMARY KEY ("PARKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("PARKING_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("PARKING_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("SINGLE_PRICE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("LAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("PARING_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_PARKING" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_RENT_CAR_ORDER
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" ADD CONSTRAINT "PK_TRIP_RENT_CAR_ORDER" PRIMARY KEY ("RENT_CAR_ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("RENT_CAR_ORDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("BEGIN_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("END_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("BEGIN_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("END_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("SEAT_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("CONTACTS_PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("CONTACTS_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("LICENSE_PLATE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_RENT_CAR_ORDER" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_STATION
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_STATION" ADD CONSTRAINT "PK_TRIP_STATION" PRIMARY KEY ("STATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_STATION" MODIFY ("STATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_STATION" MODIFY ("CUSTOM_BUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_STATION" MODIFY ("DEPART_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_STATION" MODIFY ("STATION_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_STATION" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_STATION" MODIFY ("CREATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_STATION" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_TAXI_DRIVER
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_DRIVER" ADD CONSTRAINT "PK_TRIP_TAXI_DRIVER" PRIMARY KEY ("TAXI_DRIVER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_DRIVER" MODIFY ("TAXI_DRIVER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_DRIVER" MODIFY ("LICENSE_PLATE" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_DRIVER" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_TAXI_EVALUATE
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" ADD CONSTRAINT "PK_TRIP_TAXI_EVALUATE" PRIMARY KEY ("TAXI_EVALUATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" MODIFY ("TAXI_EVALUATE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" MODIFY ("TAXI_ORDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" MODIFY ("STAR_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" MODIFY ("INS_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_EVALUATE" MODIFY ("CREATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_TAXI_ORDER
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" ADD CONSTRAINT "PK_TRIP_TAXI_ORDER" PRIMARY KEY ("TAXI_ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" MODIFY ("TAXI_ORDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" MODIFY ("BEGIN_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" MODIFY ("BEGIN_LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" MODIFY ("BEGIN_LAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" MODIFY ("END_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" MODIFY ("END_LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_ORDER" MODIFY ("END_LAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_TAXI_POSITION
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_POSITION" ADD CONSTRAINT "PK_TRIP_TAXI_POSITION" PRIMARY KEY ("TAXI_POSITION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_POSITION" MODIFY ("TAXI_POSITION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_POSITION" MODIFY ("TAXI_DRIVER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_POSITION" MODIFY ("LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_POSITION" MODIFY ("LAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_POSITION" MODIFY ("INS_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRIP_TAXI_TRAJECTORY
--------------------------------------------------------

  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" ADD CONSTRAINT "PK_TRIP_TAXI_TRAJECTORY" PRIMARY KEY ("TAXI_TRAJECTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "AKS"  ENABLE;
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" MODIFY ("TAXI_TRAJECTORY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" MODIFY ("TAXI_DRIVER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" MODIFY ("TAXI_ORDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" MODIFY ("LNG" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" MODIFY ("LAT" NOT NULL ENABLE);
 
  ALTER TABLE "IKEY_AKS"."TRIP_TAXI_TRAJECTORY" MODIFY ("INS_TIME" NOT NULL ENABLE);
